#!/usr/bin/python
# -*- coding: utf-8 -*-

import MySQLdb
from defines import *

con = MySQLdb.connect(DB_HOST, DB_USER_NAME, DB_PASSWORD, DB_DB_NAME)
with con:
	cur = con.cursor()
	cur.execute("""create table if not exists %s (
		postId INT not null,
		postInfo MEDIUMBLOB not null,
		addedDate datetime not null,
		memo VARCHAR(4096) not null,
		INDEX (addedDate)
	)""" % (TABLE_PREFETCHING_QUEUE))
	cur.execute("""create table if not exists %s (
		id INT not null primary key,
		filename VARCHAR(255) not null,
		createdDate datetime not null,
		prefetched bool not null,
		memo VARCHAR(4096) not null,
		lastActiveDate datetime not null,
		INDEX (prefetched, lastActiveDate)
	)""" % (TABLE_POST))
	cur.execute("""create table if not exists %s (
		name VARCHAR(255) not null primary key,
		beginAt datetime not null,
		finishedAt datetime not null
	)""" % (TABLE_BACKGROUND_JOBS))
	cur.execute("""create table if not exists %s (
		`key` VARCHAR(255) not null primary key,
		value MEDIUMTEXT not null
	)""" % (TABLE_KEY_VALUE_STORE))
	cur.execute("""create table if not exists %s (
		id INT not null auto_increment primary key,
		lastActiveDate datetime not null,
		isActive bool not null
	)""" % (TABLE_USER))
	cur.execute("""create table if not exists %s (
		userId INT not null,
		type INT not null,
		key1 VARCHAR(255) not null,
		INDEX (key1)
	)""" % (TABLE_USER_AUTH))
	cur.execute("""create table if not exists %s (
		userId INT not null,
		authKey VARBINARY(20) not null,
		authType INT not null,
		memo VARCHAR(4096),
		date datetime not null,
		INDEX (userId)
	)""" % (TABLE_USER_SESSION))
	cur.execute("""create table if not exists %s (
		userId INT not null,
		postId INT not null,
		isRead bool not null,
		updateDate datetime not null,
		INDEX (userId),
		UNIQUE (userId, postId)
	)""" % (TABLE_ACTIVE_ITEM))
