#!/usr/bin/python
# -*- coding: utf-8 -*-

import MySQLdb
from defines import *

con = MySQLdb.connect(DB_HOST, DB_USER_NAME, DB_PASSWORD, DB_DB_NAME)
with con:
	cur = con.cursor()
	cur.execute("""create table if not exists %s (
		postInfo MEDIUMBLOB not null,
		addedDate datetime not null,
		memo VARCHAR(4096) not null,
		INDEX (addedDate)
	)""" % (TABLE_PREFETCHING_QUEUE))
	cur.execute("""create table if not exists %s (
		id INT not null primary key,
		filename VARCHAR(255) not null,
		prefetched bool not null,
		lastActiveDate datetime not null
	)""" % (TABLE_POST))
	cur.execute("""create table if not exists %s (
		name VARCHAR(255) not null primary key,
		beginAt datetime not null,
		finishedAt datetime not null
	)""" % (TABLE_BACKGROUND_JOBS))
	cur.execute("""create table if not exists %s (
		`key` VARCHAR(255) not null primary key,
		value MEDIUMTEXT not null
	)""" % (TABLE_KEY_VALUE_STORE))
